export const DROPDOWN_ACTIONS = {
	LOADING_CONTESTS: 'LOADING_CONTESTS',
	FETCH_CONTESTS: 'FETCH_CONTESTS',
	SET_CONTESTS: 'SET_CONTESTS',
	SET_GAMETYPE: 'SET_GAMETYPE',
};

export const setGameType = (gameType: string) => ({
	type: DROPDOWN_ACTIONS.SET_GAMETYPE,
	gameType,
});
